ALTER TABLE PHONE_TABLE DROP constraint FK_FOR_ADDRESS !

ALTER TABLE ALIAS_TABLE DROP constraint FK1_FOR_CUSTOMER_TABLE !

ALTER TABLE ALIAS_TABLE DROP constraint FK2_FOR_CUSTOMER_TABLE !

ALTER TABLE FKS_ALIAS_CUSTOMER DROP constraint FK_FOR_CUSTOMER_TABLE !

ALTER TABLE FKS_ALIAS_CUSTOMER DROP constraint FK_FOR_ALIAS_TABLE !

ALTER TABLE CREDITCARD_TABLE DROP constraint FK3_FOR_CUSTOMER_TABLE !

ALTER TABLE CREDITCARD_TABLE DROP constraint FK_FOR_ORDER_TABLE !

ALTER TABLE ORDER_TABLE DROP constraint FK4_FOR_CUSTOMER_TABLE !

ALTER TABLE ORDER_TABLE DROP constraint FK0_FOR_LINEITEM_TABLE !

ALTER TABLE LINEITEM_TABLE DROP constraint FK_FOR_PRODUCT_TABLE !

ALTER TABLE LINEITEM_TABLE DROP constraint FK1_FOR_ORDER_TABLE !

ALTER TABLE CUSTOMER_TABLE DROP constraint FK5_FOR_CUSTOMER_TABLE !

ALTER TABLE CUSTOMER_TABLE DROP constraint FK6_FOR_CUSTOMER_TABLE !

ALTER TABLE FKS_ANOOP_CNOOP  DROP constraint FK2_FOR_ALIAS_TABLE !

ALTER TABLE FKS_ANOOP_CNOOP  DROP constraint FK8_FOR_CUSTOMER_TABLE !

ALTER TABLE SPOUSE_TABLE DROP constraint FK7_FOR_CUSTOMER_TABLE !

ALTER TABLE SPOUSE_TABLE DROP constraint FK_FOR_INFO_TABLE !

ALTER TABLE INFO_TABLE DROP constraint FK_FOR_SPOUSE_TABLE !

ALTER TABLE EMPLOYEE DROP constraint FK_MGR !

ALTER TABLE EMPLOYEE DROP constraint FK_DEPT !

ALTER TABLE EMPLOYEE DROP constraint FK_PROJECT !

ALTER TABLE EMPLOYEE DROP constraint FK_INS !

ALTER TABLE COMPANY DROP constraint FK_ADDRESS  !

ALTER TABLE DEPARTMENT DROP constraint FK_COMPANY !

ALTER TABLE TEAM DROP CONSTRAINT COMPANY_COMPANYID !

ALTER TABLE PERSON DROP CONSTRAINT INSURANCE_INSID !

ALTER TABLE PERSON DROP CONSTRAINT TEAM_TEAMID !

ALTER TABLE PERSON DROP CONSTRAINT PROJECT_PROJID !

ALTER TABLE PERSON_ANNUALREVIEW DROP CONSTRAINT ANNUALREVIEWS_AID !

ALTER TABLE PERSON_ANNUALREVIEW DROP CONSTRAINT PERSON_PERSONID!

ALTER TABLE PROJECT_PERSON DROP CONSTRAINT PROJ_PROJID!

ALTER TABLE PROJECT_PERSON DROP CONSTRAINT PERSONS_PERSONID!

ALTER TABLE PERSON_INSURANCE DROP CONSTRAINT P_PERSONID !

ALTER TABLE PERSON_INSURANCE DROP CONSTRAINT INS_INSID !

ALTER TABLE ORDER1 DROP CONSTRAINT FK1_FOR_ITEM !

ALTER TABLE ORDER2 DROP CONSTRAINT FK2_FOR_ITEM !

ALTER TABLE ORDER3 DROP CONSTRAINT FK3_FOR_ITEM !

ALTER TABLE BEANEJB_1X1_BI_BTOB DROP constraint FK1_FOR_AEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_BTOB DROP constraint FK2_FOR_AEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_BTOB DROP constraint FK1_FOR_BEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_BTOB DROP constraint FK2_FOR_BEJB_1X1_BI_BTOB !

ALTER TABLE BEJB_1X1_BI_BTOB DROP constraint FK_FOR_AEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_CASCADE DROP constraint FK1_FOR_AEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_BI_CASCADE DROP constraint FK2_FOR_AEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_BI_CASCADE DROP constraint FK1_FOR_BEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_BI_CASCADE DROP constraint FK2_FOR_BEJB_1X1_BI_CASCADE !

ALTER TABLE BEJB_1X1_BI_CASCADE DROP constraint FK_FOR_AEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_UNI_BTOB DROP constraint FK1_FOR_AEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1X1_UNI_BTOB DROP constraint FK2_FOR_AEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1X1_UNI_BTOB DROP constraint FK1_FOR_BEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1X1_UNI_BTOB DROP constraint FK2_FOR_BEJB_1X1_UNI_BTOB !

ALTER TABLE BEJB_1X1_UNI_BTOB DROP constraint FK_FOR_AEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB DROP constraint FK1_FOR_AEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB DROP constraint FK2_FOR_AEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB DROP constraint FK1_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB DROP constraint FK2_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB DROP constraint FK3_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB DROP constraint FK4_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEJB_1XM_BI_BTOB DROP constraint FK_FOR_AEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_CASCADE DROP constraint FK1_FOR_AEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_CASCADE DROP constraint FK2_FOR_AEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_CASCADE DROP constraint FK1_FOR_BEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_CASCADE DROP constraint FK2_FOR_BEJB_1XM_BI_CASCADE !

ALTER TABLE BEJB_1XM_BI_CASCADE DROP constraint FK_FOR_AEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_DELETE DROP constraint FK1_FOR_AEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_BI_DELETE DROP constraint FK2_FOR_AEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_BI_DELETE DROP constraint FK1_FOR_BEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_BI_DELETE DROP constraint FK2_FOR_BEJB_1XM_BI_DELETE !

ALTER TABLE BEJB_1XM_BI_DELETE DROP constraint FK_FOR_AEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_UNI_BTOB DROP constraint FK1_FOR_AEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB DROP constraint FK2_FOR_AEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB DROP constraint FK1_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB DROP constraint FK2_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB DROP constraint FK3_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB DROP constraint FK4_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEJB_1XM_UNI_BTOB DROP constraint FK_FOR_AEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB DROP constraint FK1_FOR_AEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB DROP constraint FK2_FOR_AEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB DROP constraint FK1_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB DROP constraint FK2_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB DROP constraint FK3_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB DROP constraint FK4_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEJB_MX1_UNI_BTOB DROP constraint FK_FOR_AEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_DELETE DROP constraint FK1_FOR_AEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE DROP constraint FK2_FOR_AEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE DROP constraint FK1_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE DROP constraint FK2_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE DROP constraint FK3_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE DROP constraint FK4_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEJB_MX1_UNI_DELETE DROP constraint FK_FOR_AEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_BTOB DROP constraint FK1_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB DROP constraint FK2_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB DROP constraint FK3_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB DROP constraint FK4_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB DROP constraint FK1_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB DROP constraint FK2_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB DROP constraint FK3_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB DROP constraint FK4_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE FKEYS_MXM_BI_BTOB DROP constraint FK_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE FKEYS_MXM_BI_BTOB DROP constraint FK_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_DELETE DROP constraint FK1_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE DROP constraint FK2_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE DROP constraint FK3_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE DROP constraint FK4_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE DROP constraint FK1_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE DROP constraint FK2_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE DROP constraint FK3_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE DROP constraint FK4_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE FKEYS_MXM_BI_DELETE DROP constraint FK_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE FKEYS_MXM_BI_DELETE DROP constraint FK_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_UNI_BTOB DROP constraint FK1_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB DROP constraint FK2_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB DROP constraint FK3_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB DROP constraint FK4_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB DROP constraint FK1_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB DROP constraint FK2_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB DROP constraint FK3_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB DROP constraint FK4_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE FKEYS_MXM_UNI_BTOB DROP constraint FK_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE FKEYS_MXM_UNI_BTOB DROP constraint FK_FOR_BEJB_MXM_UNI_BTOB !

DROP TABLE ADDRESS !
CREATE TABLE ADDRESS (ID VARCHAR(255) PRIMARY KEY NOT NULL, STREET VARCHAR(255) , CITY VARCHAR(255) , STATE VARCHAR(255) , ZIP VARCHAR(255) ) !

DROP TABLE CUSTOMER_TABLE !
CREATE TABLE CUSTOMER_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), COUNTRY VARCHAR(255), CODE VARCHAR(255), FK5_FOR_CUSTOMER_TABLE VARCHAR(255), FK6_FOR_CUSTOMER_TABLE VARCHAR(255)) !

DROP TABLE PHONE_TABLE !
CREATE TABLE PHONE_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, AREA VARCHAR(255) , PHONE_NUMBER VARCHAR(255) , FK_FOR_ADDRESS VARCHAR(255) ) !

DROP TABLE ALIAS_TABLE !
CREATE TABLE ALIAS_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, ALIAS VARCHAR(255) , FK1_FOR_CUSTOMER_TABLE  VARCHAR(255) , FK2_FOR_CUSTOMER_TABLE  VARCHAR(255) ) !

DROP TABLE FKS_ALIAS_CUSTOMER !
CREATE TABLE FKS_ALIAS_CUSTOMER ( FK_FOR_CUSTOMER_TABLE VARCHAR(255) , FK_FOR_ALIAS_TABLE VARCHAR(255)) !

DROP TABLE CREDITCARD_TABLE !
CREATE TABLE CREDITCARD_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, TYPE VARCHAR(255) , EXPIRES VARCHAR(255) , APPROVED NUMERIC , CREDITCARD_NUMBER VARCHAR(255) , BALANCE DOUBLE PRECISION, FK3_FOR_CUSTOMER_TABLE VARCHAR(255) , FK_FOR_ORDER_TABLE VARCHAR(255)) !

DROP TABLE ORDER_TABLE !
CREATE TABLE  ORDER_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, TOTALPRICE DOUBLE PRECISION, FK4_FOR_CUSTOMER_TABLE VARCHAR(255) , FK0_FOR_LINEITEM_TABLE VARCHAR(255)) !

DROP TABLE PRODUCT_DETAILS !
CREATE TABLE PRODUCT_DETAILS ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, WHOUSE VARCHAR(255) , LICENSE_KEY integer) !

DROP TABLE PRODUCT_TABLE !
CREATE TABLE PRODUCT_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), PRICE DOUBLE PRECISION, QUANTITY INTEGER, PNUM INTEGER, PRODUCT_TYPE VARCHAR(255), INCEPTION DATETIME NULL, SOLD DATETIME NULL, MODEL INTEGER, REV DOUBLE PRECISION ) !

DROP TABLE PRICED_PRODUCT_TABLE !
CREATE TABLE PRICED_PRODUCT_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), PRICE DOUBLE PRECISION, QUANTITY INTEGER, PNUM INTEGER ) !

DROP TABLE LINEITEM_TABLE !
CREATE TABLE LINEITEM_TABLE (ID VARCHAR(255) PRIMARY KEY NOT NULL, QUANTITY INTEGER , FK_FOR_PRODUCT_TABLE VARCHAR(255) , FK1_FOR_ORDER_TABLE VARCHAR(255)) !

ALTER TABLE CUSTOMER_TABLE add constraint FK5_FOR_CUSTOMER_TABLE Foreign Key (FK5_FOR_CUSTOMER_TABLE) references ADDRESS(ID) !

ALTER TABLE CUSTOMER_TABLE add constraint FK6_FOR_CUSTOMER_TABLE Foreign Key (FK6_FOR_CUSTOMER_TABLE) references ADDRESS(ID) !
ALTER TABLE PHONE_TABLE add constraint FK_FOR_ADDRESS Foreign Key (FK_FOR_ADDRESS) references ADDRESS(ID) !

ALTER TABLE ALIAS_TABLE add constraint FK1_FOR_CUSTOMER_TABLE Foreign Key (FK1_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(ID) !

ALTER TABLE ALIAS_TABLE add constraint FK2_FOR_CUSTOMER_TABLE Foreign Key (FK2_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(ID) !

ALTER TABLE FKS_ALIAS_CUSTOMER add constraint FK_FOR_CUSTOMER_TABLE Foreign Key (FK_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(ID) !

ALTER TABLE FKS_ALIAS_CUSTOMER add constraint FK_FOR_ALIAS_TABLE Foreign Key (FK_FOR_ALIAS_TABLE) references ALIAS_TABLE(ID) !

ALTER TABLE CREDITCARD_TABLE add constraint FK3_FOR_CUSTOMER_TABLE Foreign Key (FK3_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(ID) !

ALTER TABLE CREDITCARD_TABLE add constraint FK_FOR_ORDER_TABLE Foreign Key (FK_FOR_ORDER_TABLE) references ORDER_TABLE(ID) !

ALTER TABLE ORDER_TABLE add constraint FK4_FOR_CUSTOMER_TABLE Foreign Key (FK4_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(ID) !

ALTER TABLE ORDER_TABLE add constraint FK0_FOR_LINEITEM_TABLE Foreign Key (FK0_FOR_LINEITEM_TABLE) references LINEITEM_TABLE(ID) !

ALTER TABLE LINEITEM_TABLE add constraint FK_FOR_PRODUCT_TABLE Foreign Key (FK_FOR_PRODUCT_TABLE) references PRODUCT_TABLE(ID) !

ALTER TABLE LINEITEM_TABLE add constraint FK1_FOR_ORDER_TABLE Foreign Key (FK1_FOR_ORDER_TABLE) references ORDER_TABLE(ID) !

DROP TABLE FKS_ANOOP_CNOOP !
CREATE TABLE FKS_ANOOP_CNOOP( FK8_FOR_CUSTOMER_TABLE VARCHAR(255) , FK2_FOR_ALIAS_TABLE VARCHAR(255)) !

DROP TABLE SPOUSE_TABLE!
CREATE TABLE SPOUSE_TABLE(ID VARCHAR(255) PRIMARY KEY NOT NULL,  FIRSTNAME VARCHAR(255), MAIDENNAME VARCHAR(255), LASTNAME VARCHAR(255), SOCSECNUM VARCHAR(255), FK7_FOR_CUSTOMER_TABLE VARCHAR(255), FK_FOR_INFO_TABLE VARCHAR(255))!

DROP TABLE INFO_TABLE!
CREATE TABLE INFO_TABLE(ID VARCHAR(255) PRIMARY KEY NOT NULL, INFOSTREET VARCHAR(255), INFOCITY VARCHAR(255), INFOSTATE VARCHAR(255), INFOZIP VARCHAR(255), FK_FOR_SPOUSE_TABLE VARCHAR(255)) !

ALTER TABLE FKS_ANOOP_CNOOP add constraint FK2_FOR_ALIAS_TABLE Foreign Key (FK2_FOR_ALIAS_TABLE) references ALIAS_TABLE(ID) !

ALTER TABLE FKS_ANOOP_CNOOP add constraint FK8_FOR_CUSTOMER_TABLE Foreign Key (FK8_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(ID) !

ALTER TABLE SPOUSE_TABLE add constraint FK7_FOR_CUSTOMER_TABLE Foreign Key (FK7_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(ID) !

ALTER TABLE SPOUSE_TABLE add constraint FK_FOR_INFO_TABLE Foreign Key (FK_FOR_INFO_TABLE) references INFO_TABLE(ID) !

ALTER TABLE INFO_TABLE add constraint FK_FOR_SPOUSE_TABLE Foreign Key (FK_FOR_SPOUSE_TABLE) references SPOUSE_TABLE(ID) !

DROP TABLE EMPLOYEE !
CREATE TABLE EMPLOYEE (HIREDATE DATETIME NULL, ID INTEGER PRIMARY KEY NOT NULL, FIRSTNAME VARCHAR(255) NULL, SALARY REAL NOT NULL, LASTNAME VARCHAR(255) NULL, STATUS VARCHAR(255), FK_MGR INTEGER NULL,  FK_PROJECT INTEGER NULL, FK_INS INTEGER NULL, FK_DEPT INTEGER NULL ) !

DROP TABLE DEPARTMENT !
CREATE TABLE DEPARTMENT (NAME VARCHAR(255) NULL, ID INTEGER PRIMARY KEY NOT NULL,  COMPANY_COMPANYID INTEGER) !

DROP TABLE COFFEE !
CREATE TABLE COFFEE (ID INTEGER PRIMARY KEY NOT NULL, BRANDNAME VARCHAR(25), PRICE REAL) !

DROP TABLE COMPANY !
CREATE TABLE COMPANY (COMPANYID INTEGER PRIMARY KEY NOT NULL, NAME VARCHAR(25), ADDRESS_ID VARCHAR(255)) !

DROP TABLE PROJECT!
CREATE TABLE PROJECT (PROJID INTEGER PRIMARY KEY NOT NULL, NAME VARCHAR(25), BUDGET NUMERIC) !

DROP TABLE ANNUALREVIEW !
CREATE TABLE ANNUALREVIEW (AID INTEGER NOT NULL, SERVICE INTEGER, CONSTRAINT PK_ANNUAL PRIMARY KEY (AID)) !

DROP TABLE PERSON !
CREATE TABLE PERSON (PERSONID INTEGER NOT NULL, FIRSTNAME VARCHAR(255) NULL, LASTNAME VARCHAR(255) NULL, PROJECT_PROJID INTEGER NULL, INSURANCE_INSID INTEGER NULL, TEAM_TEAMID INTEGER NULL, CONSTRAINT PK_PERSON PRIMARY KEY (PERSONID)) !

DROP TABLE PROJECT_PERSON !
CREATE TABLE PROJECT_PERSON (PROJECTS_PROJID INTEGER , PERSONS_PERSONID INTEGER ) !

DROP TABLE PERSON_ANNUALREVIEW !
CREATE TABLE PERSON_ANNUALREVIEW (PERSON_PERSONID INTEGER, ANNUALREVIEWS_AID INTEGER) !

DROP TABLE PERSON_INSURANCE !
CREATE TABLE PERSON_INSURANCE ( PERSON_PERSONID INTEGER, INSURANCE_INSID INTEGER ) !

DROP TABLE INSURANCE !
CREATE TABLE INSURANCE (INSID INTEGER PRIMARY KEY NOT NULL, CARRIER VARCHAR(255) ) !

DROP TABLE TEAM !
CREATE TABLE TEAM (NAME VARCHAR(255) NULL, TEAMID INTEGER NOT NULL,  COMPANY_COMPANYID INTEGER, CONSTRAINT PK_TEAM PRIMARY KEY (TEAMID)) !

ALTER TABLE COMPANY ADD CONSTRAINT FK_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID) !
ALTER TABLE DEPARTMENT ADD CONSTRAINT FK_COMPANY FOREIGN KEY (COMPANY_COMPANYID) REFERENCES COMPANY (COMPANYID) !
ALTER TABLE TEAM ADD CONSTRAINT COMPANY_COMPANYID FOREIGN KEY (COMPANY_COMPANYID) REFERENCES COMPANY(COMPANYID) !

ALTER TABLE EMPLOYEE add CONSTRAINT FK_MGR FOREIGN KEY (FK_MGR) REFERENCES EMPLOYEE(ID) !
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_DEPT FOREIGN KEY (FK_DEPT) REFERENCES DEPARTMENT(ID) !
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_PROJECT FOREIGN KEY (FK_PROJECT) REFERENCES PROJECT(PROJID) !
ALTER TABLE EMPLOYEE ADD CONSTRAINT FK_INS FOREIGN KEY (FK_INS) REFERENCES INSURANCE(INSID) !

ALTER TABLE PERSON ADD CONSTRAINT TEAM_TEAMID FOREIGN KEY (TEAM_TEAMID) REFERENCES TEAM(TEAMID) !

ALTER TABLE PERSON ADD CONSTRAINT PROJECT_PROJID FOREIGN KEY (PROJECT_PROJID) REFERENCES PROJECT(PROJID) !

ALTER TABLE PERSON ADD CONSTRAINT INSURANCE_INSID FOREIGN KEY (INSURANCE_INSID) REFERENCES INSURANCE(INSID) !

ALTER TABLE PROJECT_PERSON ADD CONSTRAINT PROJ_PROJID Foreign Key (PROJECTS_PROJID) references PROJECT(PROJID) !

ALTER TABLE PROJECT_PERSON ADD CONSTRAINT PERSONS_PERSONID Foreign Key (PERSONS_PERSONID) references PERSON(PERSONID) !

ALTER TABLE PERSON_ANNUALREVIEW ADD CONSTRAINT ANNUALREVIEWS_AID Foreign Key (ANNUALREVIEWS_AID) references ANNUALREVIEW(AID) !

ALTER TABLE PERSON_ANNUALREVIEW ADD CONSTRAINT PERSON_PERSONID Foreign Key (PERSON_PERSONID) references PERSON(PERSONID)  !

ALTER TABLE PERSON_INSURANCE ADD CONSTRAINT P_PERSONID Foreign Key (PERSON_PERSONID) references PERSON(PERSONID) !

ALTER TABLE PERSON_INSURANCE  ADD CONSTRAINT INS_INSID Foreign Key (INSURANCE_INSID) references INSURANCE(INSID)  !

DROP TABLE PURCHASE_ORDER !
CREATE TABLE PURCHASE_ORDER (ID INTEGER NOT NULL, TOTAL INTEGER, CONSTRAINT PURCH_ORDER PRIMARY KEY (ID)) !

DROP TABLE PKEY !
CREATE TABLE PKEY ( PMIDINTEGER INTEGER NOT NULL, PMIDSTRING VARCHAR(25) NOT NULL, PMIDFLOAT REAL NOT NULL, BRANDNAME VARCHAR(25) , PRICE REAL , CONSTRAINT PK_PKEY PRIMARY KEY (PMIDINTEGER, PMIDSTRING, PMIDFLOAT)) !

DROP TABLE DATATYPES !
CREATE TABLE DATATYPES ( BOOLEANDATA SMALLINT NULL, CHARDATA CHAR NULL, SHORTDATA SMALLINT NULL, INTDATA INTEGER NULL, LONGDATA NUMERIC NULL, DBLDATA DOUBLE PRECISION NULL, FLOATDATA REAL NULL, ID INTEGER NOT NULL, BYTEDATA SMALLINT NULL, ENUMODATA INTEGER NULL, ENUMSDATA VARCHAR(25), CONSTRAINT PK_DATATYPE PRIMARY KEY (ID) )!

DROP TABLE DATATYPES2 !
CREATE TABLE DATATYPES2 ( DATATYPES2_ID DATETIME NOT NULL, TIMEDATA DATETIME, TSDATA DATETIME, BYTEDATA IMAGE, CHARDATA VARCHAR(448), CONSTRAINT PK_DATATYPES2 PRIMARY KEY (DATATYPES2_ID)) !

DROP TABLE GENERATOR_TABLE !
CREATE TABLE GENERATOR_TABLE (PK_COL VARCHAR(25) NOT NULL, VAL_COL INTEGER, CONSTRAINT GENERATOR_TABLE_PK PRIMARY KEY (PK_COL) ) !
INSERT into GENERATOR_TABLE(PK_COL, VAL_COL) values ('DT_ID', 1) !

DROP TABLE SEQUENCE !
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(10) NOT NULL, SEQ_COUNT INTEGER, CONSTRAINT SEQUENCE_PK PRIMARY KEY (SEQ_NAME) ) !
INSERT into SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0) !

DROP TABLE ORDER3 !
CREATE TABLE ORDER3 (ID VARCHAR(255) PRIMARY KEY NOT NULL, TOTALPRICE DOUBLE PRECISION , FK3_FOR_ITEM VARCHAR(255)) !

DROP TABLE ORDER1 !
CREATE TABLE ORDER1 (ID VARCHAR(255) NOT NULL, TOTALPRICE DOUBLE PRECISION , FK1_FOR_ITEM VARCHAR(255) ,CONSTRAINT ORDER1_PK PRIMARY KEY (ID)) !

DROP TABLE ORDER2 !
CREATE TABLE ORDER2 (ID VARCHAR(255) PRIMARY KEY NOT NULL, TOTALPRICE DOUBLE PRECISION , FK2_FOR_ITEM VARCHAR(255)) !

DROP TABLE ITEM !
CREATE TABLE ITEM (ID VARCHAR(255) PRIMARY KEY NOT NULL, ITEMNAME VARCHAR(255)) !

ALTER TABLE ORDER1 add constraint FK1_FOR_ITEM Foreign Key (FK1_FOR_ITEM) references ITEM(ID) !
ALTER TABLE ORDER2 add constraint FK2_FOR_ITEM Foreign Key (FK2_FOR_ITEM) references ITEM(ID) !
ALTER TABLE ORDER3 add constraint FK3_FOR_ITEM Foreign Key (FK3_FOR_ITEM) references ITEM(ID) !

DROP TABLE MEMBER !
CREATE TABLE MEMBER (MEMBER_ID INTEGER NOT NULL, MEMBER_NAME VARCHAR(255), DUES SMALLINT NULL, VERSION INTEGER, DONATION NUMERIC, CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID)) !

DROP TABLE ACCOUNT !
CREATE TABLE ACCOUNT (ID INTEGER NOT NULL, BALANCE DOUBLE PRECISION, DEPOSIT DOUBLE PRECISION, WITHDRAW DOUBLE PRECISION, CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID)) !

DROP TABLE BEANEJB_1X1_BI_BTOB !
CREATE TABLE BEANEJB_1X1_BI_BTOB ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC , FK1_FOR_AEJB_1X1_BI_BTOB VARCHAR(255) , FK2_FOR_AEJB_1X1_BI_BTOB VARCHAR(255) , FK1_FOR_BEJB_1X1_BI_BTOB VARCHAR(255) , FK2_FOR_BEJB_1X1_BI_BTOB VARCHAR(255) )  !

DROP TABLE AEJB_1X1_BI_BTOB !
CREATE TABLE  AEJB_1X1_BI_BTOB ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC ) !

DROP TABLE BEJB_1X1_BI_BTOB !
CREATE TABLE BEJB_1X1_BI_BTOB ( ID VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), VALUE NUMERIC , FK_FOR_AEJB_1X1_BI_BTOB VARCHAR(255) ) !


ALTER TABLE BEANEJB_1X1_BI_BTOB add constraint FK1_FOR_AEJB_1X1_BI_BTOB Foreign Key (FK1_FOR_AEJB_1X1_BI_BTOB) references AEJB_1X1_BI_BTOB(ID) !

ALTER TABLE BEANEJB_1X1_BI_BTOB add constraint FK2_FOR_AEJB_1X1_BI_BTOB Foreign Key (FK2_FOR_AEJB_1X1_BI_BTOB) references AEJB_1X1_BI_BTOB(ID) !

ALTER TABLE BEANEJB_1X1_BI_BTOB add constraint FK1_FOR_BEJB_1X1_BI_BTOB Foreign Key (FK1_FOR_BEJB_1X1_BI_BTOB) references BEJB_1X1_BI_BTOB(ID) !

ALTER TABLE BEANEJB_1X1_BI_BTOB add constraint FK2_FOR_BEJB_1X1_BI_BTOB Foreign Key (FK2_FOR_BEJB_1X1_BI_BTOB) references BEJB_1X1_BI_BTOB(ID) !

ALTER TABLE BEJB_1X1_BI_BTOB add constraint FK_FOR_AEJB_1X1_BI_BTOB Foreign Key (FK_FOR_AEJB_1X1_BI_BTOB) references AEJB_1X1_BI_BTOB(ID) !

DROP TABLE  BEANEJB_1X1_BI_CASCADE !
CREATE TABLE BEANEJB_1X1_BI_CASCADE ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC , FK1_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255) , FK2_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255) , FK1_FOR_BEJB_1X1_BI_CASCADE VARCHAR(255) , FK2_FOR_BEJB_1X1_BI_CASCADE VARCHAR(255) ) !

DROP TABLE AEJB_1X1_BI_CASCADE !
CREATE TABLE  AEJB_1X1_BI_CASCADE ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC ) !

DROP TABLE BEJB_1X1_BI_CASCADE !
CREATE TABLE BEJB_1X1_BI_CASCADE ( ID  VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), VALUE NUMERIC , FK_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255) )  !

ALTER TABLE BEANEJB_1X1_BI_CASCADE add constraint FK1_FOR_AEJB_1X1_BI_CASCADE Foreign Key (FK1_FOR_AEJB_1X1_BI_CASCADE) references AEJB_1X1_BI_CASCADE(ID) !

ALTER TABLE BEANEJB_1X1_BI_CASCADE add constraint FK2_FOR_AEJB_1X1_BI_CASCADE Foreign Key (FK2_FOR_AEJB_1X1_BI_CASCADE) references AEJB_1X1_BI_CASCADE(ID) !

ALTER TABLE BEANEJB_1X1_BI_CASCADE add constraint FK1_FOR_BEJB_1X1_BI_CASCADE Foreign Key (FK1_FOR_BEJB_1X1_BI_CASCADE) references BEJB_1X1_BI_CASCADE(ID) !

ALTER TABLE BEANEJB_1X1_BI_CASCADE add constraint FK2_FOR_BEJB_1X1_BI_CASCADE Foreign Key (FK2_FOR_BEJB_1X1_BI_CASCADE) references BEJB_1X1_BI_CASCADE(ID) !

ALTER TABLE BEJB_1X1_BI_CASCADE add constraint FK_FOR_AEJB_1X1_BI_CASCADE Foreign Key (FK_FOR_AEJB_1X1_BI_CASCADE) references AEJB_1X1_BI_CASCADE(ID) !

DROP TABLE BEANEJB_1X1_UNI_BTOB !
CREATE TABLE BEANEJB_1X1_UNI_BTOB ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC , FK1_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255) , FK2_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255) , FK1_FOR_BEJB_1X1_UNI_BTOB VARCHAR(255) , FK2_FOR_BEJB_1X1_UNI_BTOB VARCHAR(255) )  !

DROP TABLE AEJB_1X1_UNI_BTOB !
CREATE TABLE  AEJB_1X1_UNI_BTOB ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC ) !

DROP TABLE BEJB_1X1_UNI_BTOB !
CREATE TABLE BEJB_1X1_UNI_BTOB ( ID  VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), VALUE NUMERIC , FK_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255) )  !


ALTER TABLE BEANEJB_1X1_UNI_BTOB add constraint FK1_FOR_AEJB_1X1_UNI_BTOB Foreign Key (FK1_FOR_AEJB_1X1_UNI_BTOB) references AEJB_1X1_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_1X1_UNI_BTOB add constraint FK2_FOR_AEJB_1X1_UNI_BTOB Foreign Key (FK2_FOR_AEJB_1X1_UNI_BTOB) references AEJB_1X1_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_1X1_UNI_BTOB add constraint FK1_FOR_BEJB_1X1_UNI_BTOB Foreign Key (FK1_FOR_BEJB_1X1_UNI_BTOB) references BEJB_1X1_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_1X1_UNI_BTOB add constraint FK2_FOR_BEJB_1X1_UNI_BTOB Foreign Key (FK2_FOR_BEJB_1X1_UNI_BTOB) references BEJB_1X1_UNI_BTOB(ID) !

ALTER TABLE BEJB_1X1_UNI_BTOB add constraint FK_FOR_AEJB_1X1_UNI_BTOB Foreign Key (FK_FOR_AEJB_1X1_UNI_BTOB) references AEJB_1X1_UNI_BTOB(ID) !

DROP TABLE BEANEJB_1XM_BI_BTOB !
CREATE TABLE BEANEJB_1XM_BI_BTOB ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC , FK1_FOR_AEJB_1XM_BI_BTOB VARCHAR(255) , FK2_FOR_AEJB_1XM_BI_BTOB VARCHAR(255) , FK1_FOR_BEJB_1XM_BI_BTOB VARCHAR(255) , FK2_FOR_BEJB_1XM_BI_BTOB VARCHAR(255) , FK3_FOR_BEJB_1XM_BI_BTOB VARCHAR(255) , FK4_FOR_BEJB_1XM_BI_BTOB VARCHAR(255) )  !

DROP TABLE AEJB_1XM_BI_BTOB !
CREATE TABLE  AEJB_1XM_BI_BTOB ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC ) !

DROP TABLE BEJB_1XM_BI_BTOB !
CREATE TABLE BEJB_1XM_BI_BTOB ( ID  VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), VALUE NUMERIC , FK_FOR_AEJB_1XM_BI_BTOB VARCHAR(255) )  !

ALTER TABLE BEANEJB_1XM_BI_BTOB add constraint FK1_FOR_AEJB_1XM_BI_BTOB Foreign Key (FK1_FOR_AEJB_1XM_BI_BTOB) references AEJB_1XM_BI_BTOB(ID) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add constraint FK2_FOR_AEJB_1XM_BI_BTOB Foreign Key (FK2_FOR_AEJB_1XM_BI_BTOB) references AEJB_1XM_BI_BTOB(ID) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add constraint FK1_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK1_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(ID) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add constraint FK2_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK2_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(ID) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add constraint FK3_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK3_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(ID) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add constraint FK4_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK4_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(ID) !

ALTER TABLE BEJB_1XM_BI_BTOB add constraint FK_FOR_AEJB_1XM_BI_BTOB Foreign Key (FK_FOR_AEJB_1XM_BI_BTOB) references AEJB_1XM_BI_BTOB(ID) !

DROP TABLE BEANEJB_1XM_BI_CASCADE !
CREATE TABLE BEANEJB_1XM_BI_CASCADE ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC , FK1_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255) , FK2_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255) , FK1_FOR_BEJB_1XM_BI_CASCADE VARCHAR(255) , FK2_FOR_BEJB_1XM_BI_CASCADE VARCHAR(255) )  !

DROP TABLE AEJB_1XM_BI_CASCADE !
CREATE TABLE  AEJB_1XM_BI_CASCADE ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC )  !

DROP TABLE BEJB_1XM_BI_CASCADE !
CREATE TABLE BEJB_1XM_BI_CASCADE ( ID  VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), VALUE NUMERIC , FK_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255) )  !

ALTER TABLE BEANEJB_1XM_BI_CASCADE add constraint FK1_FOR_AEJB_1XM_BI_CASCADE Foreign Key (FK1_FOR_AEJB_1XM_BI_CASCADE) references AEJB_1XM_BI_CASCADE(ID) !

ALTER TABLE BEANEJB_1XM_BI_CASCADE add constraint FK2_FOR_AEJB_1XM_BI_CASCADE Foreign Key (FK2_FOR_AEJB_1XM_BI_CASCADE) references AEJB_1XM_BI_CASCADE(ID) !

ALTER TABLE BEANEJB_1XM_BI_CASCADE add constraint FK1_FOR_BEJB_1XM_BI_CASCADE Foreign Key (FK1_FOR_BEJB_1XM_BI_CASCADE) references BEJB_1XM_BI_CASCADE(ID) !

ALTER TABLE BEANEJB_1XM_BI_CASCADE add constraint FK2_FOR_BEJB_1XM_BI_CASCADE Foreign Key (FK2_FOR_BEJB_1XM_BI_CASCADE) references BEJB_1XM_BI_CASCADE(ID) !

ALTER TABLE BEJB_1XM_BI_CASCADE add constraint FK_FOR_AEJB_1XM_BI_CASCADE Foreign Key (FK_FOR_AEJB_1XM_BI_CASCADE) references AEJB_1XM_BI_CASCADE(ID) !

DROP TABLE BEANEJB_1XM_BI_DELETE !
CREATE TABLE BEANEJB_1XM_BI_DELETE ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255)  , VALUE NUMERIC , FK1_FOR_AEJB_1XM_BI_DELETE VARCHAR(255) , FK2_FOR_AEJB_1XM_BI_DELETE VARCHAR(255) , FK1_FOR_BEJB_1XM_BI_DELETE VARCHAR(255) , FK2_FOR_BEJB_1XM_BI_DELETE VARCHAR(255) )  !

DROP TABLE AEJB_1XM_BI_DELETE !
CREATE TABLE  AEJB_1XM_BI_DELETE ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC )  !

DROP TABLE BEJB_1XM_BI_DELETE !
CREATE TABLE BEJB_1XM_BI_DELETE ( ID  VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), VALUE NUMERIC , FK_FOR_AEJB_1XM_BI_DELETE VARCHAR(255) )  !

ALTER TABLE BEANEJB_1XM_BI_DELETE add constraint FK1_FOR_AEJB_1XM_BI_DELETE Foreign Key (FK1_FOR_AEJB_1XM_BI_DELETE) references AEJB_1XM_BI_DELETE(ID) !

ALTER TABLE BEANEJB_1XM_BI_DELETE add constraint FK2_FOR_AEJB_1XM_BI_DELETE Foreign Key (FK2_FOR_AEJB_1XM_BI_DELETE) references AEJB_1XM_BI_DELETE(ID) !

ALTER TABLE BEANEJB_1XM_BI_DELETE add constraint FK1_FOR_BEJB_1XM_BI_DELETE Foreign Key (FK1_FOR_BEJB_1XM_BI_DELETE) references BEJB_1XM_BI_DELETE(ID) !

ALTER TABLE BEANEJB_1XM_BI_DELETE add constraint FK2_FOR_BEJB_1XM_BI_DELETE Foreign Key (FK2_FOR_BEJB_1XM_BI_DELETE) references BEJB_1XM_BI_DELETE(ID) !

ALTER TABLE BEJB_1XM_BI_DELETE add constraint FK_FOR_AEJB_1XM_BI_DELETE Foreign Key (FK_FOR_AEJB_1XM_BI_DELETE) references AEJB_1XM_BI_DELETE(ID) !

DROP TABLE BEANEJB_1XM_UNI_BTOB !
CREATE TABLE BEANEJB_1XM_UNI_BTOB ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC , FK1_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255) , FK2_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255) , FK1_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255) , FK2_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255) , FK3_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255) , FK4_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255) )  !

DROP TABLE AEJB_1XM_UNI_BTOB !
CREATE TABLE  AEJB_1XM_UNI_BTOB ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC )  !

DROP TABLE BEJB_1XM_UNI_BTOB !
CREATE TABLE BEJB_1XM_UNI_BTOB ( ID  VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), VALUE NUMERIC , FK_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255) )  !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add constraint FK1_FOR_AEJB_1XM_UNI_BTOB Foreign Key (FK1_FOR_AEJB_1XM_UNI_BTOB) references AEJB_1XM_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add constraint FK2_FOR_AEJB_1XM_UNI_BTOB Foreign Key (FK2_FOR_AEJB_1XM_UNI_BTOB) references AEJB_1XM_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add constraint FK1_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK1_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add constraint FK2_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK2_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add constraint FK3_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK3_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add constraint FK4_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK4_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(ID) !

ALTER TABLE BEJB_1XM_UNI_BTOB add constraint FK_FOR_AEJB_1XM_UNI_BTOB Foreign Key (FK_FOR_AEJB_1XM_UNI_BTOB) references AEJB_1XM_UNI_BTOB(ID) !

DROP TABLE BEANEJB_MX1_UNI_BTOB !
CREATE TABLE BEANEJB_MX1_UNI_BTOB ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC , FK1_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255) , FK2_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255) , FK1_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255) , FK2_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255) , FK3_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255) , FK4_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255) )  !

DROP TABLE AEJB_MX1_UNI_BTOB !
CREATE TABLE  AEJB_MX1_UNI_BTOB ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC )  !

DROP TABLE BEJB_MX1_UNI_BTOB !
CREATE TABLE BEJB_MX1_UNI_BTOB ( ID  VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), VALUE NUMERIC , FK_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255) )  !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add constraint FK1_FOR_AEJB_MX1_UNI_BTOB Foreign Key (FK1_FOR_AEJB_MX1_UNI_BTOB) references AEJB_MX1_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add constraint FK2_FOR_AEJB_MX1_UNI_BTOB Foreign Key (FK2_FOR_AEJB_MX1_UNI_BTOB) references AEJB_MX1_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add constraint FK1_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK1_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add constraint FK2_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK2_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add constraint FK3_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK3_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add constraint FK4_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK4_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(ID) !

ALTER TABLE BEJB_MX1_UNI_BTOB add constraint FK_FOR_AEJB_MX1_UNI_BTOB Foreign Key (FK_FOR_AEJB_MX1_UNI_BTOB) references AEJB_MX1_UNI_BTOB(ID) !

DROP TABLE BEANEJB_MX1_UNI_DELETE !
CREATE TABLE BEANEJB_MX1_UNI_DELETE ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC , FK1_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255) , FK2_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255) , FK1_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK2_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK3_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK4_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) )  !

DROP TABLE AEJB_MX1_UNI_DELETE !
CREATE TABLE  AEJB_MX1_UNI_DELETE ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC )  !

DROP TABLE BEJB_MX1_UNI_DELETE !
CREATE TABLE BEJB_MX1_UNI_DELETE ( ID VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), VALUE NUMERIC , FK_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255))  !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add constraint FK1_FOR_AEJB_MX1_UNI_DELETE Foreign Key (FK1_FOR_AEJB_MX1_UNI_DELETE) references AEJB_MX1_UNI_DELETE(ID) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add constraint FK2_FOR_AEJB_MX1_UNI_DELETE Foreign Key (FK2_FOR_AEJB_MX1_UNI_DELETE) references AEJB_MX1_UNI_DELETE(ID) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add constraint FK1_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK1_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(ID) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add constraint FK2_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK2_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(ID) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add constraint FK3_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK3_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(ID) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add constraint FK4_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK4_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(ID) !

ALTER TABLE BEJB_MX1_UNI_DELETE add constraint FK_FOR_AEJB_MX1_UNI_DELETE Foreign Key (FK_FOR_AEJB_MX1_UNI_DELETE) references AEJB_MX1_UNI_DELETE(ID) !

DROP TABLE BEANEJB_MXM_BI_BTOB !
CREATE TABLE BEANEJB_MXM_BI_BTOB ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC , FK1_FOR_AEJB_MXM_BI_BTOB VARCHAR(255)  , FK2_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK3_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK4_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK1_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK2_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK3_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK4_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) )  !

DROP TABLE AEJB_MXM_BI_BTOB !
CREATE TABLE  AEJB_MXM_BI_BTOB ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC ) !

DROP TABLE BEJB_MXM_BI_BTOB !
CREATE TABLE BEJB_MXM_BI_BTOB ( ID  VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), VALUE NUMERIC  ) !

DROP TABLE FKEYS_MXM_BI_BTOB !
CREATE TABLE FKEYS_MXM_BI_BTOB ( FK_FOR_AEJB_MXM_BI_BTOB  VARCHAR(255), FK_FOR_BEJB_MXM_BI_BTOB  VARCHAR(255)) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add constraint FK1_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK1_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(ID) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add constraint FK2_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK2_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(ID) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add constraint FK3_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK3_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(ID) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add constraint FK4_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK4_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(ID) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add constraint FK1_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK1_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(ID) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add constraint FK2_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK2_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(ID) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add constraint FK3_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK3_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(ID) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add constraint FK4_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK4_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(ID) !

ALTER TABLE FKEYS_MXM_BI_BTOB add constraint FK_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(ID) !

ALTER TABLE FKEYS_MXM_BI_BTOB add constraint FK_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(ID) !

DROP TABLE BEANEJB_MXM_BI_DELETE !
CREATE TABLE BEANEJB_MXM_BI_DELETE ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC , FK1_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK2_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK3_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK4_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK1_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK2_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK3_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK4_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) )  !

DROP TABLE AEJB_MXM_BI_DELETE !
CREATE TABLE  AEJB_MXM_BI_DELETE ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC )  !

DROP TABLE BEJB_MXM_BI_DELETE !
CREATE TABLE BEJB_MXM_BI_DELETE ( ID  VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), VALUE NUMERIC  )  !

DROP TABLE FKEYS_MXM_BI_DELETE !
CREATE TABLE FKEYS_MXM_BI_DELETE ( FK_FOR_AEJB_MXM_BI_DELETE  VARCHAR(255), FK_FOR_BEJB_MXM_BI_DELETE  VARCHAR(255))       !

ALTER TABLE BEANEJB_MXM_BI_DELETE add constraint FK1_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK1_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(ID) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add constraint FK2_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK2_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(ID) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add constraint FK3_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK3_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(ID) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add constraint FK4_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK4_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(ID) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add constraint FK1_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK1_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(ID) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add constraint FK2_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK2_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(ID) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add constraint FK3_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK3_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(ID) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add constraint FK4_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK4_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(ID) !

ALTER TABLE FKEYS_MXM_BI_DELETE add constraint FK_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(ID) !

ALTER TABLE FKEYS_MXM_BI_DELETE add constraint FK_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(ID) !

DROP TABLE BEANEJB_MXM_UNI_BTOB !
CREATE TABLE BEANEJB_MXM_UNI_BTOB ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC , FK1_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK2_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK3_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK4_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK1_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK2_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK3_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK4_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) )  !

DROP TABLE AEJB_MXM_UNI_BTOB !
CREATE TABLE  AEJB_MXM_UNI_BTOB ( ID VARCHAR(255)  PRIMARY KEY NOT NULL, NAME VARCHAR(255) , VALUE NUMERIC )  !

DROP TABLE BEJB_MXM_UNI_BTOB !
CREATE TABLE BEJB_MXM_UNI_BTOB ( ID  VARCHAR(255) PRIMARY KEY NOT NULL, NAME VARCHAR(255), VALUE NUMERIC  )  !

DROP TABLE FKEYS_MXM_UNI_BTOB !
CREATE TABLE FKEYS_MXM_UNI_BTOB ( FK_FOR_AEJB_MXM_UNI_BTOB  VARCHAR(255), FK_FOR_BEJB_MXM_UNI_BTOB  VARCHAR(255))       !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add constraint FK1_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK1_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add constraint FK2_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK2_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add constraint FK3_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK3_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add constraint FK4_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK4_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add constraint FK1_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK1_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add constraint FK2_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK2_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add constraint FK3_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK3_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(ID) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add constraint FK4_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK4_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(ID) !

ALTER TABLE FKEYS_MXM_UNI_BTOB add constraint FK_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(ID) !

ALTER TABLE FKEYS_MXM_UNI_BTOB add constraint FK_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(ID) !


