
ALTER TABLE PHONE_TABLE drop foreign key FK_FOR_ADDRESS !

ALTER TABLE ALIAS_TABLE drop foreign key FK1_FOR_CUSTOMER_TABLE !

ALTER TABLE ALIAS_TABLE drop foreign key FK2_FOR_CUSTOMER_TABLE !

ALTER TABLE FKS_ALIAS_CUSTOMER drop foreign key FK_FOR_CUSTOMER_TABLE !

ALTER TABLE FKS_ALIAS_CUSTOMER drop foreign key FK_FOR_ALIAS_TABLE !

ALTER TABLE CREDITCARD_TABLE drop foreign key FK3_FOR_CUSTOMER_TABLE !

ALTER TABLE CREDITCARD_TABLE drop foreign key FK_FOR_ORDER_TABLE !

ALTER TABLE ORDER_TABLE drop foreign key FK4_FOR_CUSTOMER_TABLE !

ALTER TABLE ORDER_TABLE drop foreign key FK0_FOR_LINEITEM_TABLE !

ALTER TABLE LINEITEM_TABLE drop foreign key FK_FOR_PRODUCT_TABLE !

ALTER TABLE LINEITEM_TABLE drop foreign key FK1_FOR_ORDER_TABLE !

ALTER TABLE CUSTOMER_TABLE drop foreign key FK5_FOR_CUSTOMER_TABLE !

ALTER TABLE CUSTOMER_TABLE drop foreign key FK6_FOR_CUSTOMER_TABLE !

ALTER TABLE BEANEJB_1X1_BI_BTOB drop foreign key FK1_FOR_AEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_BTOB drop foreign key FK2_FOR_AEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_BTOB drop foreign key FK1_FOR_BEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_BTOB drop foreign key FK2_FOR_BEJB_1X1_BI_BTOB !

ALTER TABLE BEJB_1X1_BI_BTOB drop foreign key FK_FOR_AEJB_1X1_BI_BTOB !

ALTER TABLE BEANEJB_1X1_BI_CASCADE drop foreign key FK1_FOR_AEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_BI_CASCADE drop foreign key FK2_FOR_AEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_BI_CASCADE drop foreign key FK1_FOR_BEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_BI_CASCADE drop foreign key FK2_FOR_BEJB_1X1_BI_CASCADE !

ALTER TABLE BEJB_1X1_BI_CASCADE drop foreign key FK_FOR_AEJB_1X1_BI_CASCADE !

ALTER TABLE BEANEJB_1X1_UNI_BTOB drop foreign key FK1_FOR_AEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1X1_UNI_BTOB drop foreign key FK2_FOR_AEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1X1_UNI_BTOB drop foreign key FK1_FOR_BEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1X1_UNI_BTOB drop foreign key FK2_FOR_BEJB_1X1_UNI_BTOB !

ALTER TABLE BEJB_1X1_UNI_BTOB drop foreign key FK_FOR_AEJB_1X1_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK1_FOR_AEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK2_FOR_AEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK1_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK2_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK3_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_BTOB drop foreign key FK4_FOR_BEJB_1XM_BI_BTOB !

ALTER TABLE BEJB_1XM_BI_BTOB drop foreign key FK_FOR_AEJB_1XM_BI_BTOB !

ALTER TABLE BEANEJB_1XM_BI_CASCADE drop foreign key FK1_FOR_AEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_CASCADE drop foreign key FK2_FOR_AEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_CASCADE drop foreign key FK1_FOR_BEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_CASCADE drop foreign key FK2_FOR_BEJB_1XM_BI_CASCADE !

ALTER TABLE BEJB_1XM_BI_CASCADE drop foreign key FK_FOR_AEJB_1XM_BI_CASCADE !

ALTER TABLE BEANEJB_1XM_BI_DELETE drop foreign key FK1_FOR_AEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_BI_DELETE drop foreign key FK2_FOR_AEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_BI_DELETE drop foreign key FK1_FOR_BEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_BI_DELETE drop foreign key FK2_FOR_BEJB_1XM_BI_DELETE !

ALTER TABLE BEJB_1XM_BI_DELETE drop foreign key FK_FOR_AEJB_1XM_BI_DELETE !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK1_FOR_AEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK2_FOR_AEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK1_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK2_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK3_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_1XM_UNI_BTOB drop foreign key FK4_FOR_BEJB_1XM_UNI_BTOB !

ALTER TABLE BEJB_1XM_UNI_BTOB drop foreign key FK_FOR_AEJB_1XM_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK1_FOR_AEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK2_FOR_AEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK1_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK2_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK3_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_BTOB drop foreign key FK4_FOR_BEJB_MX1_UNI_BTOB !

ALTER TABLE BEJB_MX1_UNI_BTOB drop foreign key FK_FOR_AEJB_MX1_UNI_BTOB !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK1_FOR_AEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK2_FOR_AEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK1_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK2_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK3_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MX1_UNI_DELETE drop foreign key FK4_FOR_BEJB_MX1_UNI_DELETE !

ALTER TABLE BEJB_MX1_UNI_DELETE drop foreign key FK_FOR_AEJB_MX1_UNI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK1_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK2_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK3_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK4_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK1_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK2_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK3_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_BTOB drop foreign key FK4_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE FKEYS_MXM_BI_BTOB drop foreign key FK_FOR_AEJB_MXM_BI_BTOB !

ALTER TABLE FKEYS_MXM_BI_BTOB drop foreign key FK_FOR_BEJB_MXM_BI_BTOB !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK1_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK2_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK3_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK4_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK1_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK2_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK3_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_BI_DELETE drop foreign key FK4_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE FKEYS_MXM_BI_DELETE drop foreign key FK_FOR_AEJB_MXM_BI_DELETE !

ALTER TABLE FKEYS_MXM_BI_DELETE drop foreign key FK_FOR_BEJB_MXM_BI_DELETE !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK1_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK2_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK3_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK4_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK1_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK2_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK3_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE BEANEJB_MXM_UNI_BTOB drop foreign key FK4_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE FKEYS_MXM_UNI_BTOB drop foreign key FK_FOR_AEJB_MXM_UNI_BTOB !

ALTER TABLE FKEYS_MXM_UNI_BTOB drop foreign key FK_FOR_BEJB_MXM_UNI_BTOB !

ALTER TABLE FKS_ANOOP_CNOOP  drop foreign key FK2_FOR_ALIAS_TABLE !

ALTER TABLE FKS_ANOOP_CNOOP  drop foreign key FK8_FOR_CUSTOMER_TABLE !

ALTER TABLE SPOUSE_TABLE drop foreign key FK7_FOR_CUSTOMER_TABLE !

ALTER TABLE SPOUSE_TABLE drop foreign key FK_FOR_INFO_TABLE !

ALTER TABLE INFO_TABLE drop foreign key FK_FOR_SPOUSE_TABLE !

ALTER TABLE EMPLOYEE drop foreign key FK_MGR !

ALTER TABLE EMPLOYEE drop foreign key FK_DEPT !

ALTER TABLE EMPLOYEE drop foreign key FK_INS !

ALTER TABLE EMPLOYEE drop foreign key FK_PROJECT !

ALTER TABLE COMPANY drop foreign key FK_ADDRESS  !

ALTER TABLE DEPARTMENT drop foreign key FK_COMPANY !

ALTER TABLE TEAM DROP foreign key COMPANY_COMPANYID !

ALTER TABLE PERSON DROP foreign key INSURANCE_INSID !

ALTER TABLE PERSON DROP foreign key TEAM_TEAMID !

ALTER TABLE PERSON DROP foreign key PROJECT_PROJID !

ALTER TABLE PERSON_ANNUALREVIEW DROP foreign key ANNUALREVIEWS_AID !

ALTER TABLE PERSON_ANNUALREVIEW DROP foreign key PERSON_PERSONID!

ALTER TABLE PROJECT_PERSON DROP foreign key PROJECTS_PROJID!

ALTER TABLE PROJECT_PERSON DROP foreign key PERSONS_PERSONID!

ALTER TABLE PERSON_INSURANCE DROP foreign key PERSON_PERSONID !

ALTER TABLE PERSON_INSURANCE DROP foreign key INS_INSID !

ALTER TABLE ORDER1 DROP foreign key FK1_FOR_ITEM !

ALTER TABLE ORDER2 DROP foreign key FK2_FOR_ITEM !

ALTER TABLE ORDER3 DROP foreign key FK3_FOR_ITEM !

drop table ADDRESS  !
create TABLE ADDRESS (id VARCHAR(255) PRIMARY KEY, street VARCHAR(255), city VARCHAR(255), state VARCHAR(255), zip VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!
        
drop table PHONE_TABLE  !
create TABLE PHONE_TABLE (id VARCHAR(255) PRIMARY KEY, area VARCHAR(255), phone_number VARCHAR(255), FK_FOR_ADDRESS VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!
        
drop table CUSTOMER_TABLE  !
create TABLE CUSTOMER_TABLE (id VARCHAR(255) PRIMARY KEY, name VARCHAR(255) , country VARCHAR(255), code VARCHAR(255), FK5_FOR_CUSTOMER_TABLE VARCHAR(255), FK6_FOR_CUSTOMER_TABLE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!
         
drop table ALIAS_TABLE  !
create TABLE ALIAS_TABLE (id VARCHAR(255) PRIMARY KEY, alias VARCHAR(255), FK1_FOR_CUSTOMER_TABLE  VARCHAR(255), FK2_FOR_CUSTOMER_TABLE  VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!
         
drop table FKS_ALIAS_CUSTOMER  !
create TABLE FKS_ALIAS_CUSTOMER ( FK_FOR_CUSTOMER_TABLE VARCHAR(255) , FK_FOR_ALIAS_TABLE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table FKS_ANOOP_CNOOP !
create TABLE FKS_ANOOP_CNOOP( FK8_FOR_CUSTOMER_TABLE VARCHAR(255) , FK2_FOR_ALIAS_TABLE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table CREDITCARD_TABLE  !
create TABLE CREDITCARD_TABLE (ID VARCHAR(255) PRIMARY KEY, TYPE VARCHAR(255), EXPIRES VARCHAR(255), APPROVED NUMERIC, CREDITCARD_NUMBER VARCHAR(255), BALANCE DOUBLE PRECISION, FK3_FOR_CUSTOMER_TABLE VARCHAR(255), FK_FOR_ORDER_TABLE VARCHAR(255) ) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table ORDER_TABLE  !
create TABLE  ORDER_TABLE (ID VARCHAR(255) PRIMARY KEY, TOTALPRICE DOUBLE PRECISION , FK4_FOR_CUSTOMER_TABLE VARCHAR(255), FK0_FOR_LINEITEM_TABLE VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table PRODUCT_DETAILS !
create TABLE PRODUCT_DETAILS ( ID VARCHAR(255)  PRIMARY KEY , WHOUSE VARCHAR(255) , LICENSE_KEY INTEGER) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table PRODUCT_TABLE !
CREATE TABLE PRODUCT_TABLE (id VARCHAR(255) PRIMARY KEY, name VARCHAR(255), price float, quantity integer, pnum integer, PRODUCT_TYPE VARCHAR(255), INCEPTION DATE NULL, SOLD DATE NULL, MODEL integer, REV float ) ENGINE=innoDB DEFAULT CHARSET=latin1 !
 
DROP TABLE PRICED_PRODUCT_TABLE !
CREATE TABLE PRICED_PRODUCT_TABLE (ID VARCHAR(255) PRIMARY KEY , NAME VARCHAR(255), PRICE FLOAT, QUANTITY INTEGER, PNUM INTEGER ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table SPOUSE_TABLE !
create TABLE SPOUSE_TABLE (ID VARCHAR(255) PRIMARY KEY,  FIRSTNAME VARCHAR(255), MAIDENNAME VARCHAR(255), LASTNAME VARCHAR(255), SOCSECNUM VARCHAR(255), FK7_FOR_CUSTOMER_TABLE VARCHAR(255), FK_FOR_INFO_TABLE VARCHAR(255) ) ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table INFO_TABLE !
create TABLE INFO_TABLE (ID VARCHAR(255) PRIMARY KEY, INFOSTREET VARCHAR(255), INFOCITY VARCHAR(255), INFOSTATE VARCHAR(255), INFOZIP VARCHAR(255), FK_FOR_SPOUSE_TABLE VARCHAR(255) ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table LINEITEM_TABLE  !
create TABLE LINEITEM_TABLE (id VARCHAR(255) PRIMARY KEY, quantity integer, FK_FOR_PRODUCT_TABLE VARCHAR(255), FK1_FOR_ORDER_TABLE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
         
ALTER TABLE PHONE_TABLE add ( constraint FK_FOR_ADDRESS Foreign Key (FK_FOR_ADDRESS) references ADDRESS(id) ON DELETE CASCADE ) !

ALTER TABLE ALIAS_TABLE add ( constraint FK1_FOR_CUSTOMER_TABLE Foreign Key (FK1_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE ALIAS_TABLE add ( constraint FK2_FOR_CUSTOMER_TABLE Foreign Key (FK2_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE FKS_ALIAS_CUSTOMER  add ( constraint FK_FOR_CUSTOMER_TABLE Foreign Key (FK_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE FKS_ALIAS_CUSTOMER  add ( constraint FK_FOR_ALIAS_TABLE Foreign Key (FK_FOR_ALIAS_TABLE) references ALIAS_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE FKS_ANOOP_CNOOP  add ( constraint FK2_FOR_ALIAS_TABLE Foreign Key (FK2_FOR_ALIAS_TABLE) references ALIAS_TABLE(id) ON DELETE CASCADE)!

ALTER TABLE FKS_ANOOP_CNOOP  add (constraint FK8_FOR_CUSTOMER_TABLE Foreign Key (FK8_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(id) ON DELETE CASCADE)!

ALTER TABLE CREDITCARD_TABLE add ( constraint FK3_FOR_CUSTOMER_TABLE Foreign Key (FK3_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE CREDITCARD_TABLE add ( constraint FK_FOR_ORDER_TABLE Foreign Key (FK_FOR_ORDER_TABLE) references ORDER_TABLE(id) ON DELETE CASCADE ) !
       
ALTER TABLE ORDER_TABLE add ( constraint FK4_FOR_CUSTOMER_TABLE Foreign Key (FK4_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE ORDER_TABLE add ( constraint FK0_FOR_LINEITEM_TABLE Foreign Key (FK0_FOR_LINEITEM_TABLE) references LINEITEM_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE LINEITEM_TABLE add ( constraint FK_FOR_PRODUCT_TABLE Foreign Key (FK_FOR_PRODUCT_TABLE) references PRODUCT_TABLE(id) ON DELETE CASCADE ) !

ALTER TABLE LINEITEM_TABLE add ( constraint FK1_FOR_ORDER_TABLE Foreign Key (FK1_FOR_ORDER_TABLE) references ORDER_TABLE(id) ON DELETE CASCADE ) !
 
ALTER TABLE CUSTOMER_TABLE add ( constraint FK5_FOR_CUSTOMER_TABLE Foreign Key (FK5_FOR_CUSTOMER_TABLE) references ADDRESS(id) ON DELETE CASCADE ) !

ALTER TABLE CUSTOMER_TABLE add ( constraint FK6_FOR_CUSTOMER_TABLE Foreign Key (FK6_FOR_CUSTOMER_TABLE) references ADDRESS(id) ON DELETE CASCADE ) !
   
ALTER TABLE SPOUSE_TABLE add (constraint FK7_FOR_CUSTOMER_TABLE Foreign Key(FK7_FOR_CUSTOMER_TABLE) references CUSTOMER_TABLE(ID) ON DELETE CASCADE) ! 

ALTER TABLE SPOUSE_TABLE add (constraint FK_FOR_INFO_TABLE Foreign Key (FK_FOR_INFO_TABLE) references INFO_TABLE(ID) ON DELETE CASCADE) !

ALTER TABLE INFO_TABLE add (constraint FK_FOR_SPOUSE_TABLE Foreign Key (FK_FOR_SPOUSE_TABLE) references SPOUSE_TABLE(ID) ON DELETE CASCADE) !

drop table BEANEJB_1X1_BI_BTOB  !
create TABLE BEANEJB_1X1_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1X1_BI_BTOB VARCHAR(255), FK2_FOR_AEJB_1X1_BI_BTOB VARCHAR(255), FK1_FOR_BEJB_1X1_BI_BTOB VARCHAR(255), FK2_FOR_BEJB_1X1_BI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1X1_BI_BTOB  !
create TABLE  AEJB_1X1_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1X1_BI_BTOB  !
create TABLE BEJB_1X1_BI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1X1_BI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1X1_BI_BTOB add ( constraint FK1_FOR_AEJB_1X1_BI_BTOB Foreign Key (FK1_FOR_AEJB_1X1_BI_BTOB) references AEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_BI_BTOB add ( constraint FK2_FOR_AEJB_1X1_BI_BTOB Foreign Key (FK2_FOR_AEJB_1X1_BI_BTOB) references AEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_BI_BTOB add ( constraint FK1_FOR_BEJB_1X1_BI_BTOB Foreign Key (FK1_FOR_BEJB_1X1_BI_BTOB) references BEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_BI_BTOB add ( constraint FK2_FOR_BEJB_1X1_BI_BTOB Foreign Key (FK2_FOR_BEJB_1X1_BI_BTOB) references BEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEJB_1X1_BI_BTOB add ( constraint FK_FOR_AEJB_1X1_BI_BTOB Foreign Key (FK_FOR_AEJB_1X1_BI_BTOB) references AEJB_1X1_BI_BTOB(id) ON DELETE CASCADE ) !
   
drop table BEANEJB_1X1_BI_CASCADE  !
create TABLE BEANEJB_1X1_BI_CASCADE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255), FK2_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255), FK1_FOR_BEJB_1X1_BI_CASCADE VARCHAR(255), FK2_FOR_BEJB_1X1_BI_CASCADE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1X1_BI_CASCADE  !
create TABLE  AEJB_1X1_BI_CASCADE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1X1_BI_CASCADE  !
create TABLE BEJB_1X1_BI_CASCADE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1X1_BI_CASCADE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1X1_BI_CASCADE add ( constraint FK1_FOR_AEJB_1X1_BI_CASCADE Foreign Key (FK1_FOR_AEJB_1X1_BI_CASCADE) references AEJB_1X1_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1X1_BI_CASCADE add ( constraint FK2_FOR_AEJB_1X1_BI_CASCADE Foreign Key (FK2_FOR_AEJB_1X1_BI_CASCADE) references AEJB_1X1_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1X1_BI_CASCADE add ( constraint FK1_FOR_BEJB_1X1_BI_CASCADE Foreign Key (FK1_FOR_BEJB_1X1_BI_CASCADE) references BEJB_1X1_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1X1_BI_CASCADE add ( constraint FK2_FOR_BEJB_1X1_BI_CASCADE Foreign Key (FK2_FOR_BEJB_1X1_BI_CASCADE) references BEJB_1X1_BI_CASCADE(id)) !


ALTER TABLE BEJB_1X1_BI_CASCADE add ( constraint FK_FOR_AEJB_1X1_BI_CASCADE Foreign Key (FK_FOR_AEJB_1X1_BI_CASCADE) references AEJB_1X1_BI_CASCADE(id)) !
   
drop table BEANEJB_1X1_UNI_BTOB  !
create TABLE BEANEJB_1X1_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255), FK2_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255), FK1_FOR_BEJB_1X1_UNI_BTOB VARCHAR(255), FK2_FOR_BEJB_1X1_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1X1_UNI_BTOB  !
create TABLE  AEJB_1X1_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1X1_UNI_BTOB  !
create TABLE BEJB_1X1_UNI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1X1_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1X1_UNI_BTOB add ( constraint FK1_FOR_AEJB_1X1_UNI_BTOB Foreign Key (FK1_FOR_AEJB_1X1_UNI_BTOB) references AEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_UNI_BTOB add ( constraint FK2_FOR_AEJB_1X1_UNI_BTOB Foreign Key (FK2_FOR_AEJB_1X1_UNI_BTOB) references AEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_UNI_BTOB add ( constraint FK1_FOR_BEJB_1X1_UNI_BTOB Foreign Key (FK1_FOR_BEJB_1X1_UNI_BTOB) references BEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1X1_UNI_BTOB add ( constraint FK2_FOR_BEJB_1X1_UNI_BTOB Foreign Key (FK2_FOR_BEJB_1X1_UNI_BTOB) references BEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEJB_1X1_UNI_BTOB add ( constraint FK_FOR_AEJB_1X1_UNI_BTOB Foreign Key (FK_FOR_AEJB_1X1_UNI_BTOB) references AEJB_1X1_UNI_BTOB(id) ON DELETE CASCADE ) !

drop table BEANEJB_1XM_BI_BTOB  !
create TABLE BEANEJB_1XM_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1XM_BI_BTOB VARCHAR(255), FK2_FOR_AEJB_1XM_BI_BTOB VARCHAR(255), FK1_FOR_BEJB_1XM_BI_BTOB VARCHAR(255), FK2_FOR_BEJB_1XM_BI_BTOB VARCHAR(255), FK3_FOR_BEJB_1XM_BI_BTOB VARCHAR(255), FK4_FOR_BEJB_1XM_BI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1XM_BI_BTOB  !
create TABLE  AEJB_1XM_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table BEJB_1XM_BI_BTOB  !
create TABLE BEJB_1XM_BI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1XM_BI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
     

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK1_FOR_AEJB_1XM_BI_BTOB Foreign Key (FK1_FOR_AEJB_1XM_BI_BTOB) references AEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK2_FOR_AEJB_1XM_BI_BTOB Foreign Key (FK2_FOR_AEJB_1XM_BI_BTOB) references AEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK1_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK1_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK2_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK2_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK3_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK3_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_BI_BTOB add ( constraint FK4_FOR_BEJB_1XM_BI_BTOB Foreign Key (FK4_FOR_BEJB_1XM_BI_BTOB) references BEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEJB_1XM_BI_BTOB add ( constraint FK_FOR_AEJB_1XM_BI_BTOB Foreign Key (FK_FOR_AEJB_1XM_BI_BTOB) references AEJB_1XM_BI_BTOB(id) ON DELETE CASCADE ) !
   
drop table BEANEJB_1XM_BI_CASCADE  !
create TABLE BEANEJB_1XM_BI_CASCADE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255), FK2_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255), FK1_FOR_BEJB_1XM_BI_CASCADE VARCHAR(255), FK2_FOR_BEJB_1XM_BI_CASCADE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_1XM_BI_CASCADE  !
create TABLE  AEJB_1XM_BI_CASCADE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1XM_BI_CASCADE  !
create TABLE BEJB_1XM_BI_CASCADE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1XM_BI_CASCADE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
     

ALTER TABLE BEANEJB_1XM_BI_CASCADE add ( constraint FK1_FOR_AEJB_1XM_BI_CASCADE Foreign Key (FK1_FOR_AEJB_1XM_BI_CASCADE) references AEJB_1XM_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1XM_BI_CASCADE add ( constraint FK2_FOR_AEJB_1XM_BI_CASCADE Foreign Key (FK2_FOR_AEJB_1XM_BI_CASCADE) references AEJB_1XM_BI_CASCADE(id)) !



ALTER TABLE BEANEJB_1XM_BI_CASCADE add ( constraint FK1_FOR_BEJB_1XM_BI_CASCADE Foreign Key (FK1_FOR_BEJB_1XM_BI_CASCADE) references BEJB_1XM_BI_CASCADE(id)) !

ALTER TABLE BEANEJB_1XM_BI_CASCADE add ( constraint FK2_FOR_BEJB_1XM_BI_CASCADE Foreign Key (FK2_FOR_BEJB_1XM_BI_CASCADE) references BEJB_1XM_BI_CASCADE(id)) !

ALTER TABLE BEJB_1XM_BI_CASCADE add ( constraint FK_FOR_AEJB_1XM_BI_CASCADE Foreign Key (FK_FOR_AEJB_1XM_BI_CASCADE) references AEJB_1XM_BI_CASCADE(id)) !
   
drop table BEANEJB_1XM_BI_DELETE  !
create TABLE BEANEJB_1XM_BI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1XM_BI_DELETE VARCHAR(255), FK2_FOR_AEJB_1XM_BI_DELETE VARCHAR(255), FK1_FOR_BEJB_1XM_BI_DELETE VARCHAR(255), FK2_FOR_BEJB_1XM_BI_DELETE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_1XM_BI_DELETE  !
create TABLE  AEJB_1XM_BI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table BEJB_1XM_BI_DELETE  !
create TABLE BEJB_1XM_BI_DELETE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1XM_BI_DELETE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1XM_BI_DELETE add ( constraint FK1_FOR_AEJB_1XM_BI_DELETE Foreign Key (FK1_FOR_AEJB_1XM_BI_DELETE) references AEJB_1XM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_1XM_BI_DELETE add ( constraint FK2_FOR_AEJB_1XM_BI_DELETE Foreign Key (FK2_FOR_AEJB_1XM_BI_DELETE) references AEJB_1XM_BI_DELETE(id)) !


ALTER TABLE BEANEJB_1XM_BI_DELETE add ( constraint FK1_FOR_BEJB_1XM_BI_DELETE Foreign Key (FK1_FOR_BEJB_1XM_BI_DELETE) references BEJB_1XM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_1XM_BI_DELETE add ( constraint FK2_FOR_BEJB_1XM_BI_DELETE Foreign Key (FK2_FOR_BEJB_1XM_BI_DELETE) references BEJB_1XM_BI_DELETE(id)) !


ALTER TABLE BEJB_1XM_BI_DELETE add ( constraint FK_FOR_AEJB_1XM_BI_DELETE Foreign Key (FK_FOR_AEJB_1XM_BI_DELETE) references AEJB_1XM_BI_DELETE(id)) !
   
drop table BEANEJB_1XM_UNI_BTOB  !
create TABLE BEANEJB_1XM_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255), FK2_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255), FK1_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255), FK2_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255), FK3_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255), FK4_FOR_BEJB_1XM_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_1XM_UNI_BTOB  !
create TABLE  AEJB_1XM_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_1XM_UNI_BTOB  !
create TABLE BEJB_1XM_UNI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_1XM_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK1_FOR_AEJB_1XM_UNI_BTOB Foreign Key (FK1_FOR_AEJB_1XM_UNI_BTOB) references AEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK2_FOR_AEJB_1XM_UNI_BTOB Foreign Key (FK2_FOR_AEJB_1XM_UNI_BTOB) references AEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK1_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK1_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK2_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK2_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK3_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK3_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_1XM_UNI_BTOB add ( constraint FK4_FOR_BEJB_1XM_UNI_BTOB Foreign Key (FK4_FOR_BEJB_1XM_UNI_BTOB) references BEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEJB_1XM_UNI_BTOB add ( constraint FK_FOR_AEJB_1XM_UNI_BTOB Foreign Key (FK_FOR_AEJB_1XM_UNI_BTOB) references AEJB_1XM_UNI_BTOB(id) ON DELETE CASCADE ) !
   
drop table BEANEJB_MX1_UNI_BTOB  !
create TABLE BEANEJB_MX1_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255), FK2_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255), FK1_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255), FK2_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255), FK3_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255), FK4_FOR_BEJB_MX1_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table AEJB_MX1_UNI_BTOB  !
create TABLE  AEJB_MX1_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table BEJB_MX1_UNI_BTOB  !
create TABLE BEJB_MX1_UNI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_MX1_UNI_BTOB VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK1_FOR_AEJB_MX1_UNI_BTOB Foreign Key (FK1_FOR_AEJB_MX1_UNI_BTOB) references AEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK2_FOR_AEJB_MX1_UNI_BTOB Foreign Key (FK2_FOR_AEJB_MX1_UNI_BTOB) references AEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK1_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK1_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK2_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK2_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK3_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK3_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MX1_UNI_BTOB add ( constraint FK4_FOR_BEJB_MX1_UNI_BTOB Foreign Key (FK4_FOR_BEJB_MX1_UNI_BTOB) references BEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !


ALTER TABLE BEJB_MX1_UNI_BTOB add ( constraint FK_FOR_AEJB_MX1_UNI_BTOB Foreign Key (FK_FOR_AEJB_MX1_UNI_BTOB) references AEJB_MX1_UNI_BTOB(id) ON DELETE CASCADE ) !

drop table BEANEJB_MX1_UNI_DELETE  !
create TABLE BEANEJB_MX1_UNI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255) , FK2_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255) , FK1_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK2_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK3_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) , FK4_FOR_BEJB_MX1_UNI_DELETE VARCHAR(255) )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_MX1_UNI_DELETE  !
create TABLE  AEJB_MX1_UNI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_MX1_UNI_DELETE  !
create TABLE BEJB_MX1_UNI_DELETE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL, FK_FOR_AEJB_MX1_UNI_DELETE VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK1_FOR_AEJB_MX1_UNI_DELETE Foreign Key (FK1_FOR_AEJB_MX1_UNI_DELETE) references AEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK2_FOR_AEJB_MX1_UNI_DELETE Foreign Key (FK2_FOR_AEJB_MX1_UNI_DELETE) references AEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK1_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK1_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK2_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK2_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(id)) !


ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK3_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK3_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEANEJB_MX1_UNI_DELETE add ( constraint FK4_FOR_BEJB_MX1_UNI_DELETE Foreign Key (FK4_FOR_BEJB_MX1_UNI_DELETE) references BEJB_MX1_UNI_DELETE(id)) !

ALTER TABLE BEJB_MX1_UNI_DELETE add ( constraint FK_FOR_AEJB_MX1_UNI_DELETE Foreign Key (FK_FOR_AEJB_MX1_UNI_DELETE) references AEJB_MX1_UNI_DELETE(id)) !
   
drop table BEANEJB_MXM_BI_BTOB  !
create TABLE BEANEJB_MXM_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK2_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK3_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK4_FOR_AEJB_MXM_BI_BTOB VARCHAR(255) , FK1_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK2_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK3_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) , FK4_FOR_BEJB_MXM_BI_BTOB VARCHAR(255) )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_MXM_BI_BTOB  !
create TABLE  AEJB_MXM_BI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_MXM_BI_BTOB  !
create TABLE BEJB_MXM_BI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table FKEYS_MXM_BI_BTOB  !
create TABLE FKEYS_MXM_BI_BTOB ( FK_FOR_AEJB_MXM_BI_BTOB  VARCHAR(255), FK_FOR_BEJB_MXM_BI_BTOB  VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!    

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK1_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK1_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK2_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK2_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK3_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK3_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK4_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK4_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK1_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK1_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK2_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK2_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK3_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK3_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_BI_BTOB add ( constraint FK4_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK4_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE FKEYS_MXM_BI_BTOB add ( constraint FK_FOR_AEJB_MXM_BI_BTOB Foreign Key (FK_FOR_AEJB_MXM_BI_BTOB) references AEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE FKEYS_MXM_BI_BTOB add ( constraint FK_FOR_BEJB_MXM_BI_BTOB Foreign Key (FK_FOR_BEJB_MXM_BI_BTOB) references BEJB_MXM_BI_BTOB(id) ON DELETE CASCADE ) !
   
drop table BEANEJB_MXM_BI_DELETE  !
create TABLE BEANEJB_MXM_BI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK2_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK3_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK4_FOR_AEJB_MXM_BI_DELETE VARCHAR(255) , FK1_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK2_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK3_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) , FK4_FOR_BEJB_MXM_BI_DELETE VARCHAR(255) )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_MXM_BI_DELETE  !
create TABLE  AEJB_MXM_BI_DELETE ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!
    
drop table BEJB_MXM_BI_DELETE  !
create TABLE BEJB_MXM_BI_DELETE ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL )  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table FKEYS_MXM_BI_DELETE  !
create TABLE FKEYS_MXM_BI_DELETE ( FK_FOR_AEJB_MXM_BI_DELETE  VARCHAR(255), FK_FOR_BEJB_MXM_BI_DELETE  VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!    

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK1_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK1_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK2_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK2_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK3_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK3_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK4_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK4_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !


ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK1_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK1_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK2_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK2_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK3_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK3_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !

ALTER TABLE BEANEJB_MXM_BI_DELETE add ( constraint FK4_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK4_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !

ALTER TABLE FKEYS_MXM_BI_DELETE add ( constraint FK_FOR_AEJB_MXM_BI_DELETE Foreign Key (FK_FOR_AEJB_MXM_BI_DELETE) references AEJB_MXM_BI_DELETE(id)) !

ALTER TABLE FKEYS_MXM_BI_DELETE add ( constraint FK_FOR_BEJB_MXM_BI_DELETE Foreign Key (FK_FOR_BEJB_MXM_BI_DELETE) references BEJB_MXM_BI_DELETE(id)) !
   
drop table BEANEJB_MXM_UNI_BTOB  !
create TABLE BEANEJB_MXM_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL, FK1_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK2_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK3_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK4_FOR_AEJB_MXM_UNI_BTOB VARCHAR(255) , FK1_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK2_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK3_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) , FK4_FOR_BEJB_MXM_UNI_BTOB VARCHAR(255) )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table AEJB_MXM_UNI_BTOB  !
create TABLE  AEJB_MXM_UNI_BTOB ( id VARCHAR(255)  PRIMARY KEY, name VARCHAR(255) , value NUMERIC NOT NULL)  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table BEJB_MXM_UNI_BTOB  !
create TABLE BEJB_MXM_UNI_BTOB ( id  VARCHAR(255) PRIMARY KEY, name VARCHAR(255), value NUMERIC NOT NULL )  ENGINE=innoDB DEFAULT CHARSET=latin1!
     
drop table FKEYS_MXM_UNI_BTOB  !
create TABLE FKEYS_MXM_UNI_BTOB ( FK_FOR_AEJB_MXM_UNI_BTOB  VARCHAR(255), FK_FOR_BEJB_MXM_UNI_BTOB  VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK1_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK1_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK2_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK2_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK3_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK3_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK4_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK4_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK1_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK1_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK2_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK2_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK3_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK3_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE BEANEJB_MXM_UNI_BTOB add ( constraint FK4_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK4_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE FKEYS_MXM_UNI_BTOB add ( constraint FK_FOR_AEJB_MXM_UNI_BTOB Foreign Key (FK_FOR_AEJB_MXM_UNI_BTOB) references AEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !

ALTER TABLE FKEYS_MXM_UNI_BTOB add ( constraint FK_FOR_BEJB_MXM_UNI_BTOB Foreign Key (FK_FOR_BEJB_MXM_UNI_BTOB) references BEJB_MXM_UNI_BTOB(id) ON DELETE CASCADE ) !
   

DROP TABLE PKEY !
CREATE TABLE PKEY ( PMIDINTEGER INTEGER  NOT NULL, PMIDSTRING VARCHAR(25) NOT NULL, PMIDFLOAT REAL NOT NULL, BRANDNAME VARCHAR(255) , PRICE REAL ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE DATATYPES !
CREATE TABLE DATATYPES ( BOOLEANDATA SMALLINT NULL, CHARDATA CHAR NULL, SHORTDATA SMALLINT NULL, INTDATA INTEGER NULL, LONGDATA NUMERIC NULL, DBLDATA DOUBLE PRECISION NULL, FLOATDATA REAL NULL, ID INTEGER AUTO_INCREMENT PRIMARY KEY, ENUMODATA INTEGER NULL, ENUMSDATA VARCHAR(25), BYTEDATA SMALLINT NULL ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE DATATYPES2  !
CREATE TABLE DATATYPES2 ( DATATYPES2_ID DATE NOT NULL, TIMEDATA DATE, TSDATA DATE, BYTEDATA BLOB, CHARDATA VARCHAR(448), CONSTRAINT PK_DATATYPES2 PRIMARY KEY (DATATYPES2_ID))  ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE GENERATOR_TABLE !
CREATE TABLE GENERATOR_TABLE (PK_COL VARCHAR(10) NOT NULL, VAL_COL INTEGER ) ENGINE=innoDB DEFAULT CHARSET=latin1 !
INSERT into GENERATOR_TABLE(PK_COL, VAL_COL) values ('DT_ID', 1) !

DROP TABLE SEQUENCE !
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(10) PRIMARY KEY NOT NULL, SEQ_COUNT INTEGER) ENGINE=innoDB DEFAULT CHARSET=latin1 !
INSERT into SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0) !


DROP TABLE EMPLOYEE !
CREATE TABLE EMPLOYEE (HIREDATE DATE NULL, ID NUMERIC NOT NULL, FIRSTNAME VARCHAR(255) NULL, SALARY REAL NOT NULL, LASTNAME VARCHAR(255) NULL, STATUS VARCHAR(255), FK_MGR NUMERIC ,  FK_PROJECT INTEGER , FK_INS INTEGER , FK_DEPT NUMERIC , CONSTRAINT PK_EMPLOYEE PRIMARY KEY(ID) ) ENGINE=innoDB DEFAULT CHARSET=latin1!

DROP TABLE DEPARTMENT !
CREATE TABLE DEPARTMENT (NAME VARCHAR(255) NULL, ID NUMERIC PRIMARY KEY NOT NULL,  COMPANY_COMPANYID INTEGER) ENGINE=innoDB DEFAULT CHARSET=latin1!

DROP TABLE COFFEE !
CREATE TABLE COFFEE (ID INTEGER PRIMARY KEY NOT NULL, BRANDNAME VARCHAR(25), PRICE REAL ) ENGINE=innoDB DEFAULT CHARSET=latin1!

DROP TABLE COMPANY !
CREATE TABLE COMPANY (COMPANYID INTEGER PRIMARY KEY NOT NULL, NAME VARCHAR(25), ADDRESS_ID VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1 !
DROP TABLE TEAM !
CREATE TABLE TEAM (NAME VARCHAR(255) NULL, TEAMID INTEGER PRIMARY KEY NOT NULL,  COMPANY_COMPANYID INTEGER) ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE COMPANY ADD ( CONSTRAINT FK_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID) ON DELETE CASCADE )!
ALTER TABLE DEPARTMENT ADD ( CONSTRAINT FK_COMPANY FOREIGN KEY (COMPANY_COMPANYID) REFERENCES COMPANY (COMPANYID) ON DELETE CASCADE )!
ALTER TABLE TEAM ADD ( CONSTRAINT COMPANY_COMPANYID FOREIGN KEY (COMPANY_COMPANYID) REFERENCES COMPANY(COMPANYID) ON DELETE CASCADE ) !

DROP TABLE PROJECT!
CREATE TABLE PROJECT (PROJID INTEGER PRIMARY KEY NOT NULL, NAME VARCHAR(25), BUDGET NUMERIC ) ENGINE=innoDB DEFAULT CHARSET=latin1 !
DROP TABLE PERSON !
CREATE TABLE PERSON (PERSONID INTEGER PRIMARY KEY NOT NULL, FIRSTNAME VARCHAR(255) NULL, LASTNAME VARCHAR(255) NULL, PROJECT_PROJID INTEGER NULL, INSURANCE_INSID INTEGER NULL, TEAM_TEAMID INTEGER NULL) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE ANNUALREVIEW !
CREATE TABLE ANNUALREVIEW (AID INTEGER PRIMARY KEY NOT NULL, SERVICE INTEGER) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE INSURANCE !
CREATE TABLE INSURANCE (INSID INTEGER PRIMARY KEY NOT NULL, CARRIER VARCHAR(255) ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE PROJECT_PERSON !
CREATE TABLE PROJECT_PERSON (PROJECTS_PROJID INTEGER , PERSONS_PERSONID INTEGER ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE PERSON_ANNUALREVIEW !
CREATE TABLE PERSON_ANNUALREVIEW (PERSON_PERSONID INTEGER, ANNUALREVIEWS_AID INTEGER) ENGINE=innoDB DEFAULT CHARSET=latin1!

DROP TABLE PERSON_INSURANCE !
CREATE TABLE PERSON_INSURANCE (PERSON_PERSONID INTEGER, INSURANCE_INSID INTEGER ) ENGINE=innoDB DEFAULT CHARSET=latin1 !

DROP TABLE PURCHASE_ORDER !
CREATE TABLE PURCHASE_ORDER (ID NUMERIC NOT NULL, TOTAL INTEGER, CONSTRAINT PURCHASE_ORDER PRIMARY KEY (ID)) ENGINE=innoDB DEFAULT CHARSET=latin1 !

ALTER TABLE EMPLOYEE ADD ( CONSTRAINT FK_MGR FOREIGN KEY (FK_MGR) REFERENCES EMPLOYEE (ID) ) !

ALTER TABLE EMPLOYEE ADD ( CONSTRAINT FK_DEPT FOREIGN KEY (FK_DEPT) REFERENCES DEPARTMENT (ID) )!

ALTER TABLE EMPLOYEE ADD ( CONSTRAINT FK_PROJECT FOREIGN KEY (FK_PROJECT) REFERENCES PROJECT (PROJID) )!

ALTER TABLE EMPLOYEE ADD ( CONSTRAINT FK_INS FOREIGN KEY (FK_INS) REFERENCES INSURANCE (INSID) )!

ALTER TABLE PERSON ADD ( CONSTRAINT TEAM_TEAMID FOREIGN KEY (TEAM_TEAMID) REFERENCES TEAM(TEAMID) ) !

ALTER TABLE PERSON ADD ( CONSTRAINT PROJECT_PROJID FOREIGN KEY (PROJECT_PROJID) REFERENCES PROJECT(PROJID)) !

ALTER TABLE PERSON ADD ( CONSTRAINT INSURANCE_INSID FOREIGN KEY (INSURANCE_INSID) REFERENCES INSURANCE(INSID)) !

ALTER TABLE PROJECT_PERSON ADD ( CONSTRAINT PROJECTS_PROJID FOREIGN KEY (PROJECTS_PROJID) references PROJECT(PROJID) ) !

ALTER TABLE PROJECT_PERSON ADD ( CONSTRAINT PERSONS_PERSONID FOREIGN KEY (PERSONS_PERSONID) references PERSON(PERSONID) ) !

ALTER TABLE PERSON_ANNUALREVIEW ADD ( CONSTRAINT ANNUALREVIEWS_AID FOREIGN KEY (ANNUALREVIEWS_AID) references ANNUALREVIEW(AID))  !

ALTER TABLE PERSON_ANNUALREVIEW ADD ( CONSTRAINT PERSON_PERSONID FOREIGN KEY (PERSON_PERSONID) references PERSON(PERSONID) )  !

ALTER TABLE PERSON_INSURANCE ADD ( CONSTRAINT P_PERSONID FOREIGN KEY (PERSON_PERSONID) references PERSON(PERSONID) ) !

ALTER TABLE PERSON_INSURANCE  ADD ( CONSTRAINT INS_INSID FOREIGN KEY (INSURANCE_INSID) references INSURANCE(INSID) )  !

drop table ORDER3 !
CREATE TABLE ORDER3 (ID VARCHAR(255) PRIMARY KEY, totalPrice DOUBLE PRECISION , FK3_FOR_ITEM VARCHAR(255)) ENGINE=innoDB DEFAULT CHARSET=latin1 !

drop table ORDER1 !
CREATE TABLE ORDER1 (ID VARCHAR(255) PRIMARY KEY, totalPrice DOUBLE PRECISION , FK1_FOR_ITEM VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

drop table ORDER2 !
CREATE TABLE ORDER2 (ID VARCHAR(255) PRIMARY KEY, totalPrice DOUBLE PRECISION , FK2_FOR_ITEM VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

DROP TABLE ITEM !
CREATE TABLE ITEM (ID VARCHAR(255) PRIMARY KEY, ITEMNAME VARCHAR(255))  ENGINE=innoDB DEFAULT CHARSET=latin1!

ALTER TABLE ORDER1 add ( constraint FK1_FOR_ITEM Foreign Key (FK1_FOR_ITEM) references ITEM(ID) ) !
ALTER TABLE ORDER2 add ( constraint FK2_FOR_ITEM Foreign Key (FK2_FOR_ITEM) references ITEM(ID) ) !
ALTER TABLE ORDER3 add ( constraint FK3_FOR_ITEM Foreign Key (FK3_FOR_ITEM) references ITEM(ID) ) !

DROP TABLE MEMBER !
CREATE TABLE MEMBER (MEMBER_ID INTEGER NOT NULL, MEMBER_NAME VARCHAR(255), DUES SMALLINT, VERSION INTEGER, DONATION NUMERIC, CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID)) ENGINE=innoDB DEFAULT CHARSET=latin1 !
 
DROP TABLE ACCOUNT !
CREATE TABLE ACCOUNT (ID INTEGER NOT NULL, BALANCE DOUBLE PRECISION, DEPOSIT DOUBLE PRECISION, WITHDRAW DOUBLE PRECISION, CONSTRAINT PK_ACCOUNT PRIMARY KEY (ID)) ENGINE=innoDB DEFAULT CHARSET=latin1 !


